#!/usr/bin/env bash

# EGSwitcher - A lightweight Bash utility for managing multiple Epic Games accounts on Linux/Wine.
# Copyright (C) 2025 doccy-doc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail

# =========================
# USER PERMS CHECK
# =========================

[[ $(id -u) -ne 0 ]] || { echo "ERROR: Cannot run as root." >&2; exit 1; }
[[ $(whoami) == "$USER" ]] || { echo "ERROR: User mismatch ($USER vs $(whoami))." >&2; exit 1; }

# =========================
# GLOBAL VARIABLES
# =========================

# PROGRAM
# ========
PROG_NAME=$(basename -- "$0")
PROG_XDG_NAME="egswitcher"
VERSION="1.0.0"

# XDG FILES
# ==========
PROG_XDG_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/${PROG_XDG_NAME}"
PROG_XDG_TMP="${PROG_XDG_CACHE}/tmp"
PROG_XDG_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/${PROG_XDG_NAME}"
PROG_XDG_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/${PROG_XDG_NAME}"
ACCOUNTS_FILE="${PROG_XDG_DIR}/accounts.state"
CONFIG_FILE="${PROG_XDG_CONFIG}/${PROG_XDG_NAME}.conf"

# CONFIG VARIABLES
# =================
CONFIG_VARS=("EGS_PFX" "EGS_DEBUG") # CONFIG_FILE

# FIRST-RUN INSTALL
# ==================
#create XDG folders
[[ -d "$PROG_XDG_TMP" ]] || mkdir -p "$PROG_XDG_TMP"
[[ -d "$PROG_XDG_DIR" ]] || mkdir -p "$PROG_XDG_DIR"
[[ -d "$PROG_XDG_CONFIG" ]] || mkdir -p "$PROG_XDG_CONFIG"
#create sourced files
[[ -f "$CONFIG_FILE" ]] || install -m 644 -D <(printf "%s=\n" "${CONFIG_VARS[@]}") "$CONFIG_FILE"
[[ -f "$ACCOUNTS_FILE" ]] || install -m 600 -D /dev/null "$ACCOUNTS_FILE"

# SOURCE CONFIG FILE
# ===================
# shellcheck source=/dev/null
. "${CONFIG_FILE}" # EGS_PFX EGS_DEBUG
# FLAGS
# ======
: "${WINE_INIT:=0}"
: "${EGS_DEBUG:=0}" # CONFIG_FILE

# WINE VARS
# ==========
EGS_REG_KEY='HKCU\Software\Epic Games\Unreal Engine\Identifiers'
EGS_REG_VALUE='AccountId'
# Dynamic defaults
: "${EGS_PFX:="${HOME}/.wine"}" # CONFIG_FILE
: "${WINE_USER:="${USER}"}"
# Envar overrides
EGS_PFX="${EGSPFX:-$EGS_PFX}"
EGS_DEBUG="${EGSDEBUG:-$EGS_DEBUG}"

# PFX FILES
# ==========
INI_FILE="GameUserSettings.ini"
# Dynamic defaults
: "${EGS_USERDIR:="${EGS_PFX}/drive_c/users"}"
: "${EGS_LOCALDATA:="${EGS_USERDIR}/${WINE_USER}/AppData/Local"}"
: "${EGS_APPDATA:="${EGS_LOCALDATA}/EpicGamesLauncher/Saved"}"
: "${EGS_CONFIG_DIR:="${EGS_APPDATA}/Config/WindowsEditor"}"
: "${EGS_CONFIG_FILE:="${EGS_CONFIG_DIR}/${INI_FILE}"}"

# TIMERS
# =======
SHUTDOWN_TIMEOUT=30

# =========================
# MESSAGE HANDLERS
# =========================

die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
warn() { printf 'WARNING: %s\n' "$*" >&2; }
info() { printf 'INFO: %s\n' "$*" >&2; }
success() { printf 'SUCCESS: %s\n' "$*" >&2; }
debug() { [[ "$EGS_DEBUG" = "1" ]] && printf 'DEBUG: ' >&2 && printf '%q ' "$@" >&2 && printf '\n' >&2 || true; }

# =========================
# BOOTSTRAP
# =========================

check_dep() {
    command -v "$1" &>/dev/null || die "Missing dependency: $1 not installed"
}

init_deps() {
    local dep
    for dep in "$@"; do
        case "$dep" in
            wine)
                check_dep "wine"
                check_dep "wineserver"
                check_dep "winedbg"
                ;;
            file)
                check_dep "rsync"
                ;;
            *)
                die "Internal error: Unknown dependency group '$dep'"
                ;;
        esac
    done
}

# trap and delete temp files on exit
trap 'rm -rf "${PROG_XDG_TMP}"' EXIT

# =========================
# VALIDATION
# =========================

sanitise_sed_path() {
    local path="$1"
    path="${path%/}"
    path="${path%\\}"
    # printf '%s\n' "$path" | sed 's/[\\&/'"'"']/\\&/g'
    printf '%s\n' "$path" | sed "s/[\\\\&/'\$\`]/\\\\&/g; s/'/'\\\\\\\''/g"
}

guard_config_file() {
    for var in "${CONFIG_VARS[@]}"; do
         grep -q "^${var}=" "$CONFIG_FILE" || die "Config corrupted: missing $var"
    done
    return 0
}

validate_account_name() {
    local name="$1"
    [[ "$name" =~ ^[a-zA-Z0-9][a-zA-Z0-9_-]{0,62}$ ]] || return 1
    return 0
}

guard_accounts_file() {
    local marks names ids

    [[ -s "$ACCOUNTS_FILE" ]] || return 0

    marks=$(grep -c '^\* ' "$ACCOUNTS_FILE" || true)
    [[ "$marks" -le 1 ]] || die "accounts.db corrupted: multiple active (*) entries"

    names=$(awk '{print $2}' "$ACCOUNTS_FILE" | sort | uniq -d || true)
    [[ -z "$names" ]] || die "accounts.db corrupted: duplicate account names"

    ids=$(awk '{print $3}' "$ACCOUNTS_FILE" | sort | uniq -d || true)
    [[ -z "$ids" ]] || die "accounts.db corrupted: duplicate account IDs"

    awk '
        NF==0 {next}
        NF!=3 {exit 1}
        $1!="*" && $1!="-" {exit 1}
    ' "$ACCOUNTS_FILE" || die "accounts.db corrupted: invalid line format"
}

validate_prefix() {
    local new_pfx="${1:-$EGS_PFX}"
    [[ -d "${new_pfx}/drive_c/users" ]] || { debug "Cannot find users directory in path: ${new_pfx}" && return 1 ; }
    return 0
}

# =========================
# INITIALISATION
# =========================

init_egs_env() {
    local wine_user base_dir localdata ans

    # Skip if init already done
    [[ "$WINE_INIT" -eq 1 ]] && return 0

    # Guard against invalid ephemeral override
    [[ -n "${EGSPFX:-}" ]] && { validate_prefix "$EGSPFX" || die "Invalid override prefix: ${EGSPFX}" ; }

    # Validate prefix
    if ! validate_prefix; then
        # Prompt for valid prefix
        while true; do
            read -rp "Would you like to edit the prefix path? [y/N] " ans
            case "$ans" in
                y|Y)
                    # new prefix wizard
                    info "Starting wizard..."
                    prompt_new_prefix
                    break
                    ;;
                x|X|n|N)
                    die "Aborted. Cannot continue without a prefix"
                    ;;
                *)
                    warn "Unrecognised input: $ans. Please enter Y or N "
                    ;;
            esac
        done
    fi

    # Apply the validated prefix state
    export WINEPREFIX="$EGS_PFX"
    export WINEDEBUG="-winediag"
    EGS_USERDIR="${EGS_PFX}/drive_c/users"
    debug "Using WINEPREFIX: $WINEPREFIX"

    # Ask WINE for username
    wine_user="$(wine whoami 2>/dev/null | awk -F "\\" '{print $NF}' | tr -d '\r\n[:space:]')" || true
    if [[ -n "$wine_user" && -d "$EGS_USERDIR/$wine_user" ]]; then
        WINE_USER="$wine_user"
        debug "Detected WINE whoami user: $wine_user"
    else
        # Fallback: check user directories for username
        debug "WINE whoami failed. Using heuristic fallback"
        for dir in "$EGS_USERDIR"/*/; do
            [[ -d "$dir" ]] || continue
            base_dir="$(basename "$dir")"
            [[ "$base_dir" == "Public" || "$base_dir" == "Default" ]] && continue
            WINE_USER="$base_dir"
            debug "Heuristic match found. Using: $base_dir"
            break
        done
    fi

    [[ -n "$WINE_USER" ]] || die "Failed to detect Wine user directory"

    # wine reg query for LOCALAPPDATA
    localdata="$(wine reg query "HKCU\\Volatile Environment" /v LOCALAPPDATA 2>/dev/null | awk -F' ' '/REG_SZ/ {print $NF}' | sed -e 's/\r//g' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')" || true
    [[ -n "$localdata" ]] || die "Registry key for %LOCALAPPDATA% missing"
    debug "Registry LOCALAPPDATA: $localdata"
    EGS_LOCALDATA="$(winepath -u "$localdata")" || die "winepath failed to convert Windows path to Linux path"
    debug "LOCALAPPDATA resolves to: ${EGS_LOCALDATA}"
    EGS_APPDATA="${EGS_LOCALDATA}/EpicGamesLauncher/Saved"
    [[ -d "$EGS_APPDATA" ]] || die "Can not find Epic Games %LOCALAPPDATA% directory. Is your prefix corrupt?"

    # set prefix paths
    EGS_CONFIG_DIR="${EGS_APPDATA}/Config/WindowsEditor"
    EGS_CONFIG_FILE="${EGS_CONFIG_DIR}/${INI_FILE}"

    # flag init complete
    WINE_INIT=1
}

# =========================
# CRUD
# =========================

# READ
# =====
account_by_id() {
    guard_accounts_file
    awk -v id="$1" '$3==id {print $2; exit}' "$ACCOUNTS_FILE"
}

account_by_name() {
    guard_accounts_file
    awk -v n="$1" '$2==n {print $3; exit}' "$ACCOUNTS_FILE"
}

account_exists() {
    guard_accounts_file
    awk -v n="$1" '$2==n {found=1; exit} END {exit found ? 0 : 1}' "$ACCOUNTS_FILE"
}

active_account() {
    guard_accounts_file
    awk '$1=="*" {print $2; exit}' "$ACCOUNTS_FILE"
}

# CREATE
# =======
construct_entry() {
    local name="$1" uuid="$2" active="$3" mark="-"
    [[ "$active" == "true" ]] && mark="*"

    printf "%s %s %s\n" "$mark" "$name" "$uuid"
}

commit_entry() {
    guard_accounts_file
    local name="$1" uuid="$2" active="${3:-true}" tmp="${PROG_XDG_TMP}/accounts-upsert.tmp.$$"  line
    line=$(construct_entry "$name" "$uuid" "$active")

    awk -v n="$name" -v L="$line" '
        BEGIN { found=0 }
        $2 == n { print L; found=1; next }
        { print }
        END { if (!found) print L }
    ' "$ACCOUNTS_FILE" > "$tmp" && mv "$tmp" "$ACCOUNTS_FILE"
}

# UPDATE
# =======
set_inactive() {
    guard_accounts_file
    local name="$1" uuid
    uuid="$(account_by_name "$name")"

    [[ -n "$uuid" ]] || die "Cannot disable non-existent account: '$name'"
    commit_entry "$name" "$uuid" "false"
}

set_active() {
    guard_accounts_file
    local name="$1" uuid old_name
    uuid="$(account_by_name "$name")"
    old_name="$(active_account)"

    [[ -n "$uuid" ]] || die "Cannot activate non-existent account: '$name'"
    [[ -n "$old_name" ]] && set_inactive "$old_name"
    commit_entry "$name" "$uuid" "true"
}

# DELETE
# =======
delete_entry() {
    guard_accounts_file
    local name="$1" tmp="${PROG_XDG_TMP}/accounts-delete.tmp.$$"

    awk -v n="$name" '$2 != n {print}' "$ACCOUNTS_FILE" >"$tmp" || die "Failed to create temp file"
    mv -- "$tmp" "$ACCOUNTS_FILE" || die "Failed to update accounts file"
}

# =========================
# FILE MANIPULATION
# =========================

save_account_files() {
    guard_accounts_file
    init_egs_env
    local name="$1"
    local store="${PROG_XDG_DIR}/${name}"

    debug "Syncing $name from $EGS_CONFIG_FILE to $store"

    mkdir -p "$store"
    [[ -f "$EGS_CONFIG_FILE" ]] || die "No $INI_FILE to save"
    rsync -a "$EGS_CONFIG_FILE" "$store/"
}

load_account_files() {
    guard_accounts_file
    init_egs_env
    local name="$1"
    local store="${PROG_XDG_DIR}/${name}"

    debug "Syncing $name from $store to $EGS_CONFIG_FILE"
    mkdir -p "$EGS_CONFIG_DIR"
    rsync -a "${store}/${INI_FILE}" "$EGS_CONFIG_DIR/"
    debug "Account \"$name\" synced"
}

save_config_files() {
    guard_config_file
    local key="$1" value="$2" san_value
    san_value=$(sanitise_sed_path "$value")

    debug "Updating ${key} to ${value}"
    sed -i "s/^${key}=.*/${key}='${san_value}'/" "$CONFIG_FILE"
    debug "Config ${key} updated"
}

# =========================
# WINE REQUESTS
# =========================

is_egs_running() {
    init_egs_env

    if  winedbg --command "info proc" 2>/dev/null |
        grep -qi 'EpicGamesLauncher\.exe'; then
        debug "winedbg: Epic Games Launcher is running"
        return 0
    else
        debug "winedbg: Epic Games Launcher process not found"
        return 1
    fi
}

kill_egs() {
    init_egs_env
    local tries=15 i
    local delay=$((SHUTDOWN_TIMEOUT / tries))

    # Stage 0: nothing running
    ! is_egs_running && { debug "No Epic Games process found. Skipping kill_egs"; return 0; }

    # Stage 1: attempt graceful shutdown, then recheck
    info "Attempting to close Epic Games. Wait up to ${SHUTDOWN_TIMEOUT}s..."
    wine taskkill /im EpicGamesLauncher.exe /t /f &>/dev/null || true

    printf "Trying" >&2
    for ((i= 1; i<=tries; i++)); do
        sleep "$delay"
        printf "." >&2
        ! is_egs_running && success "Epic Games Closed" && return 0
    done

    # If we get here, it failed to shut down
    # Stage 2: kill wineserver
    printf "\n" >&2
    warn "Epic Games Launcher did not exit after ${SHUTDOWN_TIMEOUT}s."
    info "Force killing wineserver. Wait up to ${SHUTDOWN_TIMEOUT}s..."
    if ! timeout 5 wineserver -w &>/dev/null; then
        debug "wineserver -w timeout reached; firing wineserver -k"
        wineserver -k &>/dev/null || true
    fi

    printf "Trying" >&2
    for ((i=1; i<=tries; i++)); do
        sleep "$delay"
        printf "." >&2
        ! is_egs_running && printf "\n" >&2 && success "Epic Games Closed" && return 0
    done

    printf "\n" >&2
    die "Failed to terminate Epic Games Launcher. Aborted."
}

get_hkey_id() {
    init_egs_env
    local hkey hkey_masked wine_status

    hkey=$(wine reg query "$EGS_REG_KEY" /v "$EGS_REG_VALUE" 2>/dev/null)
    wine_status=$?
    hkey=$(awk '/REG_SZ/ {print $NF}' <<< "$hkey" | tr -d '\r')

    if [[ -n "$hkey" ]]; then
        hkey_masked="${hkey:0:4}****${hkey: -4}"
        debug "Registry $EGS_REG_VALUE: $hkey_masked"
    else
        debug "Could not retrieve hkey from WINE registry"
    fi

    printf '%s' "$hkey"
    return "$wine_status"
}

set_hkey_id() {
    init_egs_env
    local uuid="${1:-}"

    wine reg add "$EGS_REG_KEY" /v "$EGS_REG_VALUE" /t REG_SZ /d "$uuid" /f >/dev/null
}

# =========================
# COMMANDS
# =========================

prompt_new_prefix() {
    local new_pfx

    while true; do
        read -re -p "Enter Wine prefix path: " new_pfx
        if validate_prefix "$new_pfx"; then
            EGS_PFX="$new_pfx"
            save_config_files "EGS_PFX" "$new_pfx"
            return 0
        fi
        warn "Invalid prefix path: ${new_pfx}. Please try again:"
    done
}

# prompt_create_unknown() {
#     init_egs_env
#     local uuid="$1" name ans
#
#     read -rp "Unrecognised Epic account detected. Create new entry? [y/N] " ans
#     [[ "$ans" =~ ^[Yy]$ ]] || return 1
#
#     # Prompt for new name
#     while true; do
#         read -rp "Account name: " name
#         # Validate user input
#         if ! validate_account_name "$name"; then
#             warn "Invalid account name: ${name}. Please try again:"
#         elif account_exists "$name"; then
#             warn "The name ${name} already exists. Please try again:"
#         else
#             break
#         fi
#     done
#
#     save_account_files "$name"
#     commit_entry "$name" "$uuid" "true"
#     set_active "$name"
#     success "Created new account: $name"
# }

handle_unknown_session() {
    init_deps "file"
    guard_accounts_file
    local hkey="$1" target_name="${2:-}" new_name

    # Path A: Name provided. Check name is allowed.
    if [[ -n "$target_name" ]] && validate_account_name "$target_name" && ! account_exists "$target_name"; then
        new_name="$target_name"
    else
        [[ -n "$target_name" ]] && warn "Invalid account name: ${target_name}. Please try again."
        # Path B: No name provided (or validation failed). Prompt for one.
        while true; do
            read -rp "Account name: " new_name
            if ! validate_account_name "$new_name"; then
                warn "Invalid account name: ${new_name}. Please try again:"
            elif account_exists "$new_name"; then
                warn "The name ${new_name} already exists. Please try again:"
            else
                break
            fi
        done
    fi

    save_account_files "$new_name"
    commit_entry "$new_name" "$hkey" "true"
    set_active "$new_name"
    success "Registered unknown session as '$new_name'."
    return 0
}

cmd_new() {
    # Check if we have exactly 1 argument
    [[ "$#" -le 1 ]] || die "Usage: ${PROG_NAME} new [name]"
    init_deps "wine" "file"
    guard_accounts_file
    init_egs_env
    local new_name="$1" old_name hkey existing ans

    # validate name
    # [[ -n $new_name ]] && { validate_account_name "$new_name" || { warn "Invalid name ${new_name}. Try again" && new_name="" ; } ; }
    if [[ -n "$new_name" ]] && ! validate_account_name "$new_name"; then
        warn "Invalid name: ${new_name}"
        new_name=""
    fi

    # No name prompt
    if [[ -z "$new_name" ]]; then
        while true; do
            read -rp "Enter name for new account: " new_name
            validate_account_name "$new_name" && break
            warn "Invalid account name. Please try again:"
        done
    fi

    old_name=$(active_account)
    hkey=$(get_hkey_id) || debug "Registry key not found. Assuming virgin launcher"

    validate_account_name "$new_name" || die "invalid account name: $new_name"
    account_exists "$new_name" && die "Name already exists"
    kill_egs

    if [[ -n "$hkey" ]]; then
        existing=$(account_by_id "$hkey")
        if [[ -n "$existing" ]]; then
            save_account_files "$existing"
        else
            # Ask user what to do with unknown account
            while true; do
                read -rp "Unrecognised session detected. Claim as '$new_name'? [y/N] " ans
                case "$ans" in
                    y|Y)
                        info "Creating new account: $new_name"
                        handle_unknown_session "$hkey" "$new_name" || die "Aborted. Unable to claim account. Try again"
                        # Terminate here, since the intended goal is complete.
                        exit 0
                        ;;
                    x|X|n|N)
                        warn "Abandoned existing account"
                        break
                        ;;
                    *)
                        warn "Unrecognised input: $ans. Please enter Y or N: "
                        ;;
                esac
            done
        fi
    fi

    [[ -n "$old_name" ]] && set_inactive "$old_name"
    [[ -n "$hkey" ]] && set_hkey_id
    rm -f "${EGS_CONFIG_FILE}"

    success "Launcher cleared. Please login to Epic Games Launcher now"
    while true; do
        read -rp "Done? [y = save / x = abort] " ans
        case "$ans" in
            y|Y)
                info "Creating new account: $new_name"
                cmd_save "$new_name"
                # terminate on job done
                exit 0
                ;;
            x|X|n|N)
                info "Aborted. Attempting to restore account: $old_name"
                kill_egs
                if [[ -n "$old_name" ]]; then
                    cmd_load "$old_name"
                    die "Aborted. Restored ${old_name}"
                else
                    info "No previous account to load. Cleared Epic Games Launcher state"
                    exit 0
                fi
                ;;
            *)
                warn "Unrecognised input: $ans. Please enter Y or X "
                ;;
        esac
    done
}

cmd_save() {
    # Check if we have lte 1 arguments
    [[ "$#" -le 1 ]] || die "Usage: ${PROG_NAME} save [name]"
    init_deps "wine" "file"
    guard_accounts_file
    init_egs_env
    local name="${1:-}" hkey active_name uuid active

    [[ -n "$name" ]] && { validate_account_name "$name" || die "invalid account name: $name" ; }
    hkey=$(get_hkey_id) || die "Epic registry key not found. If this is a fresh install, please log in first."
    [[ -n "$hkey" ]] || die "No Epic account logged in"
    active_name=$(account_by_id "$hkey")

    # No name entered. check active account
    if [[ -z "$name" ]]; then
        info "Name not set. Resolving..."
        if [ -n "$active_name" ]; then
            info "Found existing $active_name"
            name="$active_name"
        else
            info "Unknown account found. Starting wizard..."
            cmd_new
            return # not really needed since this is a handover
        fi
    fi

    # Name entered. Find account name
    if account_exists "$name"; then
        info "Found account. Resolving..."
        uuid=$(account_by_name "$name")
        # Ensure IDs match
        [[ "$uuid" = "$hkey" ]] || die "Account $name exists with different ID"
    else
        info "Account $name not found."
        # Name not found. Check ID
        [[ -z "$active_name" ]] || die "Account already saved under name '$active_name'"
        # name and ID are unique, handover to cmd_new
        info "Unknown account found. Starting wizard..."
        cmd_new "$name"
        return # not really needed since this is a handover
    fi

    # Commit
    active=$(active_account)
    save_account_files "$name"
    [[ -n "$active" ]] && [[ "$active" != "$name" ]] && set_inactive "$active"
    commit_entry "$name" "$hkey" "true"
    success "Saved account: '$name'."
}

cmd_load() {
    # Check if we have exactly 1 argument
    [[ "$#" -eq 1 ]] || die "Usage: ${PROG_NAME} load <name>"
    init_deps "wine" "file"
    guard_accounts_file
    init_egs_env
    local name="$1" uuid hkey active_name ans

    validate_account_name "$name" || die "invalid account name: $name"
    account_exists "$name" || die "Account not found"
    uuid=$(account_by_name "$name")
    hkey=$(get_hkey_id) || die "Epic registry key not found. If this is a fresh install, please log in first."
    kill_egs

    # Check for active account
    if [[ -n "$hkey" ]]; then
        active_name=$(account_by_id "$hkey")
        #check if account is in list
        if account_exists "$active_name"; then
            save_account_files "$active_name"
        else
            # Ask user what to do with unknown account
            while true; do
                read -rp "Unrecognised session detected. Save before proceeding? [y/N] " ans
                case "$ans" in
                    y|Y)
                        info "Starting wizard..."
                        handle_unknown_session "$hkey" || die "Aborted. Unable to claim account. Try again"
                        break
                        ;;
                    x|X|n|N)
                        warn "Abandoned existing account"
                        break
                        ;;
                    *)
                        warn "Unrecognised input: $ans. Please enter Y or N: "
                        ;;
                esac
            done
        fi
    fi

    # Load
    set_hkey_id "$uuid"
    load_account_files "$name"
    set_active "$name"
    success "Loaded account: '$name'. You can now launch your game."
}

cmd_delete() {
    # Check if we have exactly 1 argument
    [[ "$#" -eq 1 ]] || die "Usage: ${PROG_NAME} delete <name>"
    guard_accounts_file
    local name="$1"

    validate_account_name "$name" || die "invalid account name: $name"
    account_exists "$name" || die "Account not found"

    # Check against active
    [[ "$(active_account || true)" != "$name" ]] || die "Cannot delete active account"

    # Delete
    delete_entry "$name"
    rm -rf -- "${PROG_XDG_DIR:?}/${name}"
    success "Deleted account: $name"
}

cmd_rename() {
    # Check if we have exactly 2 arguments
    [[ "$#" -eq 2 ]] || die "Usage: ${PROG_NAME} rename <old_name> <new_name>"
    guard_accounts_file
    local old_name="$1" new_name="$2"

    validate_account_name "$new_name" || die "invalid account name: $new_name"
    validate_account_name "$old_name" || die "invalid account name: $old_name"
    account_exists "$old_name" || die "Source name $old_name not found"
    ! account_exists "$new_name" || die "Target name $new_name already exists"

    # Rename
    mv -- "${PROG_XDG_DIR}/${old_name}" "${PROG_XDG_DIR}/${new_name}"

# TODO: ADD FUNCTIONS delete_entry + commit_entry (with test for *) #
# Leaving atomic sed inplace as it is less prone to DB corruption.  #
# Would require single-use function "edit_entry" to be atomic.      #
# ================================================================= #
    sed -i "s/^\\([*-]\\) $old_name /\\1 $new_name /" "$ACCOUNTS_FILE"
# ================================================================= #
    success "Renamed $old_name to $new_name"
}

cmd_list() {
    guard_accounts_file

    printf "%-8s %-20s %s\n" STATUS NAME ID
    printf "%-8s %-20s %s\n" ------ ---- --
    while read -r mark name id; do
        status=$([ "$mark" = "*" ] && echo ACTIVE || echo "")
        printf "%-8s %-20s %s\n" "$status" "$name" "${id: 0:4}...${id: -4:4}"
    done <"$ACCOUNTS_FILE"
}

cmd_config() {
    [[ $# -le 2 ]] || die "Usage: ${PROG_NAME} config [<key> <value>]. e.g. config pfx \"${HOME}/.wine\""
    guard_config_file
    local key_suffix="${1:-}" value="${2:-}" key_exists=0 key_name

    # If no arguments, print friendly config list
    if [[ $# -lt 1 ]]; then
    info 'Config file (key: value): ' && sed -r 's/^(EGS_)?([^=]+)=/\L\2\E: /' "$CONFIG_FILE"
    return
    fi

    # create key name from suffix
    declare -u "key_name=EGS_${key_suffix}"

    # Test key against config array
    for source_key in "${CONFIG_VARS[@]}"; do
        [[ "$source_key" == "$key_name" ]] && key_exists=1 && break
    done

    # filter for invalid key
    [[ "$key_exists" -eq 1 ]] || die "Invalid key: '$key_suffix'. Valid options: ${CONFIG_VARS[*]}"

    # Prompt user for value if not provided
    if [[ -z "$value" ]]; then
        debug "No value given for key: ${key_name}"
        while true; do
            read -re -p "Enter the new ${key_suffix} value: " value
            case "$key_suffix" in
                # special case for pfx
                "pfx")
                    if ! validate_prefix "$value"; then
                        warn "Invalid path. Please try again:"
                        continue
                    fi
                    ;;
                # everything else
                *)
                    if [[ -z "$value" ]]; then
                        warn "Value cannot be empty. Please try again:"
                        continue
                    fi
                    ;;
            esac
            break
        done
    fi



    # special check for prefix
    [[ "$key_suffix" == "pfx" ]] && { validate_prefix "$value" || die "Invalid prefix: ${value}" ; }

    # set new values
    # declare -g "${key_name}=\"${value}\""
    printf -v "$key_name" '%s' "$value"
    save_config_files "$key_name" "$value"

    success "Successfully updated $key_suffix."
}

cmd_help() {
        cat <<EOF

Commands:
  new <name>            Create a new account with name <name>
                        Example: $PROG_NAME new MyAccount

  save [name]           Save the current account. Optionally specify <name>
                        If specified <name> does not exist, a new account will be created
                        Examples:
                          $PROG_NAME save                 # Save current account using existing active name
                          $PROG_NAME save ExistingAccount # Same as: $PROG_NAME save
                          $PROG_NAME save NewAccount      # Save new account with name NewAccount

  load <name>           Load an existing account by name
                        Example: $PROG_NAME load MyAccount

  delete <name>         Delete an existing account (cannot delete the active account)
                        Example: $PROG_NAME delete MyAccount

  rename <old> <new>    Rename an account from <old> to <new>
                        Example: $PROG_NAME rename OldName NewName

  config                Show all config options
                        Example: $PROG_NAME config

  config <key> [value]  Change a config <key> to [value]. Will prompt for [value] if not specified.
                        Examples:
                          $PROG_NAME config pfx \"$HOME/.wine\"
                          $PROG_NAME config debug 1

  list                  List all saved accounts and the currently active one
                        Example: $PROG_NAME list

EOF
}

cmd_desc(){
    cat <<EOF

EGSwitcher
A tool for swapping Epic Games accounts in the Epic Games Launcher without having to manually logout and login each time. Works on Linux with either WINE or proton.
Copyright (C) 2025 doccy-doc. License: GPL-3.0-only

EOF
}

# =========================
# MAIN
# =========================
CMD="${1:-}"
shift || : # Discard the command name

case "$CMD" in
    new)    cmd_new "$@" ;;
    save)   cmd_save "$@" ;;
    load)   cmd_load "$@" ;;
    delete) cmd_delete "$@" ;;
    rename) cmd_rename "$@" ;;
    config)   cmd_config "$@" ;;
    list)   cmd_list ;;
    -v|--version)
        echo "$VERSION"
        exit 0
    ;;
    -h|--help)
        cmd_desc
        cmd_help
        exit 0
        ;;
    *)
        if [ -n "${CMD}" ] ; then
            warn "Syntax error: command '$CMD' not recognised"
        else
            cmd_desc
        fi
        cmd_help
        exit 1
        ;;
esac
